name       : vlc-pause-click-plugin
version    : 2.2.0
release    : 2
source     :
    - https://github.com/nurupo/vlc-pause-click-plugin/archive/2.2.0.tar.gz : 2a2cd76bc0bc10cb5f7c2143ae8508008c5a100f9a9c19b4fbc2c517983ded4c
homepage   : https://github.com/nurupo/vlc-pause-click-plugin
license    : LGPL-2.1-or-later
component  : multimedia.video
summary    : Plugin for VLC that pauses/plays video on mouse click
description: |
    Plugin for VLC that pauses/plays video on mouse click. Please read https://github.com/nurupo/vlc-pause-click-plugin usage section for instructions on how to enable this plugin.
builddeps  :
    - pkgconfig(vlc-plugin)
build      : |
    %make
install    : |
    %make_install
