name       : vlc-pause-click-plugin
version    : 2.1.0
release    : 1
source     :
    - https://github.com/nurupo/vlc-pause-click-plugin/archive/2.1.0.tar.gz : cebd9c0fe6273f4ff8cd2e114b4edc22376ce48d7c64b846391db71d80353bc7
license    : LGPL-2.1-or-later
component  : multimedia.video
summary    : Plugin for VLC that pauses/plays video on mouse click
description: |
    Plugin for VLC that pauses/plays video on mouse click. Please read https://github.com/nurupo/vlc-pause-click-plugin usage section for instructions on how to enable this plugin.
builddeps  :
    - pkgconfig(vlc-plugin)
build      : |
    %make
install    : |
    %make_install
